### ISSUE TITLE
How long does ImageNet experiments take?

### ISSUE THREAD

**Issue by JosephKJ** [DonkeyShot21/UNO#10]
Hi Enrico, 

Thanks again for your nice work and clean code.

I am just wondering long does the ImageNet experiments take? Lets say the ImageNet-A. And, what GPU are you using?

Thanks,
Joseph

**Comment by DonkeyShot21** [comment]
Hi,

Thanks for your interest in our work.

Last time I ran it took around 3 days on a single RTX A6000 for each split. You can make it slightly faster by running with a lower number of heads (maybe 2 instead of 4), the results won't change much.

Enrico

**Comment by JosephKJ** [comment]
Many thanks for your response, Enrico.
