### ISSUE TITLE
Clarification question on num_large_crops

### ISSUE THREAD

**Issue by JosephKJ** [DonkeyShot21/UNO#12]
Hi Enrico,

Just a clarification question. If I understand correctly, `num_large_crops` basically controls the number of augmented versions of an image. Can you confirm? 

As `num_large_crops` is set to 2, we basically have two two augmented versions of the same image in each mini-batch. These are indeed used for swapped prediction. Is my understanding correct?

Please do get back when you get a chance.

Thanks,
Joseph

**Comment by DonkeyShot21** [comment]
Yes, `num_large_crops` controls the number of large crops that are used for generating the pseudo labels. There is also `num_small_crops` that controls the number of small crops for multicrop. The small crops are not used to generate pseudo labels, their output is only compared with the output of the pseudo-labels generated with the large crops.

**Comment by JosephKJ** [comment]
Many thanks for clarifying, Enrico!
