### ISSUE TITLE
UNO_V2 results

### ISSUE THREAD

**Issue by ziyunli-2023** [DonkeyShot21/UNO#13]
For uno_v2 results on cifar100, is the acc you provide the mean of multiple runs and take the average for the best head? Do you also have the standard deviation?
And I also want to know if the ACC is chosen by the best validation epoch or the last epoch?

**Comment by DonkeyShot21** [comment]
Hi, I just ran it once for each setting so I do not have the std. I reported the accuracy after the last epoch.
