### ISSUE TITLE
The results on CIFAR10

### ISSUE THREAD

**Issue by kleinzcy** [DonkeyShot21/UNO#14]
Hi, author:

Thanks for your nice code. I benifit a lot from your code. 

For UNOv2, I can reimplement the results of CIFAR100, but I can't reimplement the results of CIFAR10 (93.6±0.2), which is worse than UNOv1 (96.1±0.5). I have try a lot times but I havn't figure out why.

I would very appreciate it if you can provide some help.

**Comment by DonkeyShot21** [comment]
Hi! Yes, the results for UNO v2 are worse than UNO v1 on CIFAR10. I think it is just a matter of parameters. I honestly think CIFAR10 is not a great benchmark for NCD because it is quite saturated and it doesn't provide much insight.

**Comment by kleinzcy** [comment]
Thanks for your reply, I also think this CIFAR10 is close to saturation. At the same time, Imagenet1k-882-30 is also approaching saturation.
