### ISSUE TITLE
Apply to a custom dataset 

### ISSUE THREAD

**Issue by hosea7456** [DonkeyShot21/UNO#5]
Hi, thanks for your great job!
I wonder if this implementation can be use to detect a total new class without train, just use the pre-trained model? 
Thank you!

**Comment by DonkeyShot21** [comment]
Hi, thank you for your kind words. I don't know if I understand correctly, but the answer is probably no. You need to pre-train the model with supervision, and then you need to train on the labeled and unlabeled set jointly to discover the new classes.
